### PR TITLE
Add new field "Empty" to Repository structure

### PR DESCRIPTION
**Pull request by lafriks**
Add new field where to return repo.IsBare boolean from Gitea API

### CODE REVIEW

**Comment by bkcsoft** [comment]
`IsBare` is a very specific thing, and not to be confused with a repo being empty :)

But LGTM 👍

**Comment by lunny** [comment]
Why it's a string type not a bool?

**Comment by lafriks** [comment]
ouch, sry, fixed to boolean

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
No `empty` in github's API v3.

**Comment by guyzmo** [comment]
@lunny indeed there's no empty, I use `size` from that API. I like the `empty` property, as it makes it explicit when you read the code.

**Comment by guyzmo** [comment]
cf the following tickets on gogs:

* https://github.com/gogits/go-gogs-client/pull/64
* https://github.com/gogits/gogs/pull/4484

**Pull request merged**
