### PR TITLE
Implement more Issue endpoints

### PR DESCRIPTION
**Pull request by bkcsoft**
See gogits/gogs#3688

### CODE REVIEW

**Review by metalmatze — APPROVED** [review]
LGTM

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
LGTM again

**Comment by bkcsoft** [comment]
Gonna add some Lint-comments for this before merging

**Comment by lunny** [comment]
I will send a PR at once to fix most lint errors. So let's LGTM this at first.

**Comment by bkcsoft** [comment]
@lunny +1

**Comment by lunny** [comment]
Please rebase.

**Comment by tboerger** [comment]
LGTM, but needs rebase.

**Comment by lunny** [comment]
You have to add comment on the methods since we have add golint check on drone.

**Comment by bkcsoft** [comment]
Rebased
@lunny fixed up all lint-comments for that file 🙂

**Pull request merged**
