### PR TITLE
webhook tag sha fix

### PR DESCRIPTION
**Pull request by bkcsoft**
https://github.com/go-gitea/gitea/issues/286

### CODE REVIEW

**Comment by strk** [comment]
LGTM

**Comment by tboerger** [comment]
Shouldn't that be SHA?

**Comment by tboerger** [comment]
But you still get my LGTM

**Comment by lunny** [comment]
@tboerger golint PASS :)

**Comment by bkcsoft** [comment]
@tboerger It should indeed be `SHA` 😆

**Comment by lunny** [comment]
@bkcsoft You can send another PR. :)

**Pull request merged**
