### PR TITLE
Rename source-dir to 'api'

### PR DESCRIPTION
**Pull request by bkcsoft**
This makes it easier in `gitea` to see what is API-stuff and what isn't, without having to rename everything.

### CODE REVIEW

**Comment by tboerger** [comment]
There is still package gitea inside of the files

**Comment by bkcsoft** [comment]
@tboerger hehe, code-reviews are nice :trollface:

**Comment by lunny** [comment]
I think this PR is no need. Just keep the gitea name for identifier.

**Comment by strk** [comment]
On Mon, Nov 07, 2016 at 06:42:24AM -0800, Lunny Xiao wrote:

> I think this PR is no need. Just keep the gitea name for identifier.

+1

**Pull request closed without merging**
