### PR TITLE
Modified assignees field in issue struct for preperation of go-gitea/gitea#1884

### PR DESCRIPTION
**Pull request by kolaente**
I'm currently implementing go-gitea/gitea#1884, this pr should be merged before the one in the gitea project.

### CODE REVIEW

**Comment by thehowl** [comment]
Wouldn't this break the API?

**Comment by kolaente** [comment]
Yes. But is there another possibility? These are breaking changes.

**Comment by thehowl** [comment]
I'd suggest keeping the assignee and having ExtraAssignees, being an array. Assignee will be the first, ExtraAssignees will be the rest.

**Comment by kolaente** [comment]
Honestly, this sound like a hack, not a proper solution. We could keep `Assignee` for a limited amount of time (and setting it to something like "This is deprecated. Use Assignees", but I'd prefer not to do this), but if we want to make it clean, we have to delete `Assignee` in favour of `Assignees` (array).

**Comment by thehowl** [comment]
Sure, that sounds more ideal. Although, breaking changes in the API before v2 are a big NO from me.

**Comment by lunny** [comment]
@kolaente you can add a migration on gitea repository.

**Comment by lunny** [comment]
And you can keep `Assignee` as the first assignees for keeping compitable

**Comment by kolaente** [comment]
Ok, so here's what I do: I'll add `Assignees` (will be an array) and keep `Assignee` (single user object). `Assignee` will contain the first assignee, `Assignees` will contain all assignees, including the first one.

**Review by thehowl — APPROVED** [review]

**Review by appleboy — APPROVED** [review]

**Comment by kolaente** [comment]
Thanks!

**Pull request merged**
