### PR TITLE
Add api lfs locks struct

### PR DESCRIPTION
**Pull request by sapk**
Needed for https://github.com/go-gitea/gitea/issues/2725

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lafriks** [comment]
LGTM

**Comment by ethantkoenig** [comment]
@sapk Thanks for this PR.

A friendly reminder that these definitions should have swagger docs if they are ever used in API endpoints (right now they're not, but in the future they may be).

**Comment by sapk** [comment]
@ethantkoenig yes I think of it but I didn't add it since they are not under gitea api root /api/v1 but relative to repository url and documented under git lfs api.

**Pull request merged**
