### PR TITLE
Added Tree API functionality

### PR DESCRIPTION
**Pull request by Kasi-R**
Allows the use of the Tree API through the SDK.

https://github.com/go-gitea/gitea/pull/4185
https://github.com/go-gitea/git/pull/123

### CODE REVIEW

**Comment by techknowlogick** [comment]
This seems to be a duplicate of #94

**Comment by Kasi-R** [comment]
Ah, my bad, i didn't notice that. I assumed there wasn't a counterpart for trees in the sdk since there wasn't one in gitea. Might also be worth considering this PR also has support for recursively iterating down subtrees. 

https://developer.github.com/v3/git/trees/#get-a-tree-recursively

**Comment by techknowlogick** [comment]
@lunny this has recursive functionality in tree fetch. Should your PR #94 be closed so we can use this one?

**Comment by lunny** [comment]
It seems #94 has been merged?

**Comment by lafriks** [comment]
Closing this one than?

**Comment by techknowlogick** [comment]
@lafriks yes, it seems so. The recursion can be added in a new PR later.

**Pull request closed without merging**
