### PR TITLE
Add new API 'ServerVersion'

### PR DESCRIPTION
**Pull request by typeless**
For https://github.com/go-gitea/gitea/pull/741

### CODE REVIEW

**Comment by lunny** [comment]
lint error.

**Comment by typeless** [comment]
Fixed.

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by appleboy** [comment]
make L-G-T-M

**Comment by strk** [comment]
Wasn't a /version endpoint added recently, togheter with the
relative API test ? Or was it part of another PR (integration tests?) ?

**Pull request merged**
