### PR TITLE
Added Parent property to the repo API

### PR DESCRIPTION
**Pull request by guyzmo**
cf gogits/gogs#4484
cf gogits/go-gogs-client#64
cf go-gitea/gitea#1687

replaces #58

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by guyzmo** [comment]
I just changed the content, to expose Repository* BaseRepo as 'parent' property, instead of an id. because that's more restful.

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
LGTM

**Pull request merged**
